version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db

  webhook_setup:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
      - RAILWAY_PUBLIC_DOMAIN=${RAILWAY_PUBLIC_DOMAIN}
    command: python railway_webhook_setup.py
    depends_on:
      - web

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: