[deploy]
startCommand = "python fix-distutils.py && gunicorn --bind 0.0.0.0:${PORT:-5000} --timeout 120 --workers 2 --reuse-port main:app"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[build]
builder = "dockerfile"
buildCommand = "python fix-distutils.py"

[variables]
PORT = "5000"
PYTHON_VERSION = "3.10.13"