[build]
  builder = "NIXPACKS"
  
[deploy]
  numReplicas = 1
  healthcheckPath = "/"
  healthcheckTimeout = 200
  restartPolicyType = "ON_FAILURE"
  
[nixpacks]
  apt = ["python3-distutils", "chromium-browser", "chromium-chromedriver"]
  python = { version = "3.10" }  # تغییر نسخه Python به 3.10 که سازگاری بیشتری دارد

[phases.setup]
  cmds = [
    "apt-get update",
    "apt-get install -y python3-distutils chromium-browser chromium-chromedriver"
  ]