[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --reuse-port --reload main:app"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10