[deploy]
startCommand = "python fix-distutils.py && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --reuse-port main:app"
healthcheckPath = "/healthz"
healthcheckTimeout = 60
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[build]
builder = "dockerfile"
buildCommand = "python fix-distutils.py"