# تنظیمات کاملاً ساده و بدون پیچیدگی برای Railway
[deploy]
# استفاده از Dockerfile بدون دستور شروع اضافی
builder = "dockerfile"
# کاملاً غیرفعال کردن healthcheck
healthcheckDisabled = true
# تنظیم نوع راه‌اندازی مجدد
restartPolicyType = "always"

# متغیرهای محیطی ضروری
[variables]
PORT = "5000"
PYTHON_VERSION = "3.10.13"